geographika/mappyfile

mappyfile/pprint.py, tests/maps_downloader.py, tests/test_msautotest.py, tests/test_ordereddict.py, tests/test_sample_maps.py, tests/test_snippets.py, tests/test_transformer.py, tox.ini
I provide some fixes in order to make this library compatible with Python3. I also:
- corrected the tox.ini file so I could run tests with the `tox` command
- mark some tests as xfail since from comments in them, I understood that they can't pass yet.
Some tests are still failing on Python 2 and 3. Since I don't know wether this is expected, I didn't mark them as xfail.
Would you be interested in enabling travis-ci on this project? If so, I can provide a PR for that. I probably should wait for all the tests to pass or mark the failing ones as xfail.
=> Python3 support

docs/examples/search.py, docs/index.rst, mappyfile/__init__.py, mappyfile/utils.py
- Add a findall method that returns an iterator. This method can be used
to find all layers with an attribute that match the given value.
- Export it in __init__.py to make it easily accesible
- Document the querying of mapfiles.
=> Add a way to find all layers matching an attribute

mappyfile/parser.py, mappyfile/utils.py, tests/samples/include1_nested_path.map, tests/samples/mapfile_include/include/include3_nested_path.map, tests/samples/mapfile_include/include2_nested_path.map, tests/test_sample_maps.py
Not sure what you tried to accomplish with cwd, append absolute paths?
According to me in mapfile you have either
- relative paths
- absolute paths
It seems that it was overriden every time when calling `parse_file`, which is not something I'd expect and I couldn't find any test for cwd argument.
Hope that you are happy with these changes.
In the utils section I added all the options you can give the parser (namely `add_linebreaks` for `loads` and `expand_includes` + `add_linebreaks` for `load`)
DOC:
http://mapserver.org/mapfile/include.html
```
Supported in versions 4.10 and higher.
The name of the file to be included MUST be quoted (single or double quotes).
Includes may be nested, up to 5 deep.
File location can be given as a full path to the file, or (in MapServer >= 4.10.1) as a path …
```
=> Add support for relative path for nested include

mappyfile/mapfile.lalr.g
Required for parsing text like:
CLASS
EXPRESSION ( "[building]" NE NULL)
END
=> LALR now recognizes NULL (or null) as a value

.travis.yml, mappyfile/mapfile.earley.g, mappyfile/mapfile.lalr.g, tests/test_snippets.py, tox.ini
I found a bunch of missing expressions
See:
http://mapserver.org/mapfile/expressions.html#arithmetic-expressions-that-return-a-logical-value
=> Add support for missing arithmetic expressions and run flake8 within tox

mappyfile/transformer.py
Otherwise you can't put `ü` and so on in expressions in py2.
=> Enable the parsing of non-ascii chars

mappyfile/mapfile.lalr.g, tests/test_expressions.py
Allows expressions (and unquoted strings in general) to contain `:`.
Fixes  https://github.com/geographika/mappyfile/issues/56
=> test and fix for issue #56

mappyfile/schemas/join.json, mappyfile/schemas/layer.json
mappyfile: Version: 0.8.2
fix: schema layer.json for joins tag
fix: schema join.json for connectiontype tag
Note: The validate function does not manage the tag: joins and connectiontype, while the transform fonction (map to json) does it.
Reference: https://mapserver.org/mapfile/join.html
Error received on the validate function:
```
{'error': "'joins' does not match any of the regexes: '^__[a-z]+__$'", 'message': 'ERROR: Invalid value in LAYER'}
{'error': "'connectiontype' does not match any of the regexes: '^__[a-z]+__$'", 'message': 'ERROR: Invalid value in JOIN'}
```
MapFile abstract:
```
JOIN
NAME 'table_join'
CONNECTION "dbname=bd_test host=host_test port=5432 user=mapserver password={***}"
CONNECTIONTYPE postgresql
TABLE 'sch.table_join'
FROM 'no_link'
TO 'no_link'
TYPE ONE-TO-MANY …
```
=> fix: json schema for join tag

mappyfile/pprint.py
mappyfile: Version: 0.8.3
fix: add the object JOINS inside Hidden Container list
Issue: Bad mapfile format on bad conversion of object to mapfile output.
Resolution: The joins object tag must be managed as layers, outputformats, ....
relate at : 
- 90741fdae8c41633431ee6c3283e355258c2d7c3
- #87 
Bad output in mapfile:
```
JOINS "DefaultOrderedDict(<class 'mappyfile.ordereddict.CaseInsensitiveOrderedDict'>, CaseInsensitiveOrderedDict([('__type__', 'join'), ('__comments__', OrderedDict()), ('name', 'table_join'), ('connection', 'dbname=bd_test host=host_test port=5432 user=mapserver password={***}'), ('connectiontype', 'postgresql'), ('table', 'sch.table_join'), ('from', 'no_link'), ('to', 'no_link'), ('type', 'ONE-TO-MANY'), ('template', '../gabarits/gabarit_join.html')]))"
```
Sample …
=> fix: add the object JOINS inside Hidden Container list

mappyfile/mapfile.lalr.g, tests/test_expressions.py
Allows the parser to recognise list expressions with spaces in the attribute names
=> Issue #89: fix for spaces in list attributes

docs/client.rst, docs/validation.rst, mappyfile/cli.py, mappyfile/schemas/class.json, mappyfile/schemas/label.json, mappyfile/schemas/symbol.json, mappyfile/utils.py, mappyfile/validator.py, tests/mapfiles/profiler.py, tests/test_validation.py
Allow validation against different versions of MapServer, for example validating Mapfiles for MapServer 7.0, or for 7.2. 
A new version parameter can be passed to the Validator class or used on the command line.
=> Add validation based on MapServer version

mappyfile/mapfile.lalr.g, mappyfile/pprint.py, mappyfile/transformer.py, tests/test_snippets.py
`OFFSET` and `POLAROFFSET` allow the following attribute pairs `[double|attribute] [double|attribute]` - combinations of bound attributes and values. This pull request allows these to be parsed correctly. See #114.
=> Add example and parsing for mixed attribute pairs

docs/api/main.rst, docs/development.rst, docs/schemas.rst, docs/schemas/mapfile.json, docs/scripts/class_diagrams.py, docs/scripts/create_diagram.py, docs/scripts/make_json_schema.py, docs/scripts/xsdschema.py, mappyfile.pyproj, mappyfile/__init__.py, mappyfile/schemas/label.json, mappyfile/schemas/layer.json, mappyfile/schemas/legend.json, mappyfile/schemas/map.json, mappyfile/schemas/querymap.json, mappyfile/schemas/scalebar.json, mappyfile/schemas/symbol.json, mappyfile/schemas/symbolset.json, mappyfile/schemas/web.json, mappyfile/utils.py, tests/test_snippets.py, tests/test_utils.py, tests/test_validation.py
Adds a new `create` function that allows Mapfile objects to be created with their default values:
```python
>>> import json
>>> import mappyfile
>>> m = mappyfile.create("map", version=8.0)
>>> print(mappyfile.dumps(m))
MAP
ANGLE 0
NAME "MS"
DEFRESOLUTION 72
MAXSIZE 4096
DEBUG 0
RESOLUTION 72
IMAGETYPE "png"
SIZE -1 -1
END
```
Updates schema objects to have default values for keywords based on MapServer output and Mapfile docs.
=> Add default values to schema and a new create function

.gitignore, mappyfile/pprint.py, mappyfile/utils.py, tests/test_pprint.py
This change aligns values "column-like" at an index n * indent. 
This improves readability a lot.
=> Feature: align values in column

mappyfile/__init__.py, mappyfile/ordereddict.py, mappyfile/pprint.py, mappyfile/tokens.py, mappyfile/utils.py, tests/test_pprint.py, tox.ini
Hello,
got some new feature: groups complex types (those that end with 'END') together at the end and thus shifts the "simple" key-value pairs in front of them. 
Also increases readability and creates a clear separation of simple from complex types in the pretty printed result.
The branch I created for it is based on thorag76_1, the one you already accepted.
Attached please find a sample before and after map to illustrate.
[after.map.txt](https://github.com/geographika/mappyfile/files/8062792/after.map.txt)
[before.map.txt](https://github.com/geographika/mappyfile/files/8062793/before.map.txt)
.
=> New feature: group complex types at the end

docs/schemas/mapfile-latest.json, docs/schemas/mapfile-schema-7-6.json, docs/schemas/mapfile-schema-8-0.json, mappyfile/schemas/composite.json, mappyfile/validator.py, tests/test_validation.py
Fixes #144 by adding in missing keyword `compfilter`. As these are functions which can have variable values e.g. `COMPFILTER "blur(10)"` an enum cannot be used. 
Update also adds an enumerated list for `compop`. 
Finally, fixes a caching bug where if the same `Validation` object is used for different schema versions the same cached schema was returned. Now caching is done on a per version basis.
=> Add COMPOSITE validation

docs/schemas/mapfile-latest.json, docs/schemas/mapfile-schema-7-6.json, docs/schemas/mapfile-schema-8-0.json, mappyfile.pyproj, mappyfile/pprint.py, mappyfile/schemas/composite.json, mappyfile/tokens.py, tests/test_snippets.py
Fixes for #150
- Multiple `COMPFILTER`s can be included in the block (there were no examples of these in docs or msautotest)
- `COMPOP` values were an enumerated list, but they should still be quoted in the output
Added a test for the above based on https://gist.github.com/LarsSchy/4aa75fd2a6bc7eb01a7cff9beb64b59a
=> Updates for COMPOSITE blocks

mappyfile/utils.py, tests/test_utils.py
Currently, `findunique()` throws a `TypeError` if any of the queried items do not have the key. My expectation was that these itemswould be ignored.
=> Support querying items without the given key in utils.findunique()

mappyfile.pyproj, mappyfile/utils.py, tests/test_utils.py
This allows updating objects with defaults without overwriting existing values:
```
mappyfile.update(d1, d2, overwrite=False)
```
See test case for example.
=> Add option to avoid overwriting values in a dict with the update method

mappyfile/__init__.py, mappyfile/dictutils.py, tests/mapfiles/itasca2.map, tests/test_dictutils.py
Fix bug when running `findall` and properties are missing from some objects e.g. 
```
MAP
LAYER
NAME "Layer1"
TYPE POLYGON
GROUP "test"
END
LAYER
NAME "Layer2"
TYPE POLYGON
GROUP "1test"
END
LAYER
NAME "Layer3"
TYPE POLYGON
GROUP "test2"
END
LAYER
NAME "Layer4"
TYPE POLYGON
END
END
```
Prior to the fix the following error would be returned:
```
138     """
--> 139     return [item for item in lst if item[key.lower()] in value]
140 
141 
TypeError: 'in <string>' requires string as left operand, not CaseInsensitiveOrderedDict
```
=> Ensure findall works when properties are missing

mappyfile.pyproj, mappyfile/validator.py, tests/test_validation.py
CI started failing when testing with Python 3.13, so ensure the full schema and all references are loaded to avoid proxies which cause `TypeError: Object of type dict is not JSON serializable` errors when using `json.dumps(deref_schema)`. 
See notes at https://github.com/gazpachoking/jsonref/issues/70.
=> Turn off proxies and lazy_load in jsonref

.github/workflows/main.yml, docs/examples/animation/animated_buffer.py, docs/examples/api/adding_values_test.py, docs/examples/api/search_test.py, docs/examples/geometry/geometry.py, docs/examples/helper.py, docs/examples/image_from_mapfile.py, docs/scripts/class_diagrams.py, mappyfile/dictutils.py, mappyfile/ordereddict.py, mappyfile/validator.py, misc/docs_parser.py, run_local.ps1, tests/test_config.py, tests/test_validation.py
Various mypy fixes required following updates to mypy dependency.
=> Add mypy type fixes

.github/workflows/main.yml, docs/scripts/make_json_schema.py, mappyfile/validator.py, pyproject.toml, setup.py
Removes `jsonref` dependency which has sone issues (with fixes not yet deployed to a PyPI release). 
Instead, use a custom ref resolver function with caching. This also improves performance of the test suite, as previously cached `.json` schema files used for validation weren't used by `jsonref` and had to be opened again. 
Before:
`255 passed, 2 xfailed in 102.19s (0:01:42)`
After:
`255 passed, 2 xfailed in 97.85s (0:01:37)`
=> Remove dependency on jsonref

docs/HISTORY.rst, docs/schemas.rst, mappyfile/utils.py, run_local.ps1, tests/test_utils.py
**Breaking Change** - `mappyfile.create` now creates an empty block by default. Pass `add_default=True` to include the default MapServer parameters.
=> Only add default MapServer values explicitly when using `create` function
